### PR TITLE
added correct link fixed issue #653

### PR DESCRIPTION
**Pull request by Srishti-j18**
I was following the guide, but  it was not clear to me that I should start a local registry to actually perform the tasks, will be great if we can make that more clear to the reader.

### CODE REVIEW

**Review by AidanDelaney — APPROVED** [review]
Thanks for this.  Our tests run a local registry, but we never make that clear to the user!

**Comment by AidanDelaney** [comment]
I'm hoping that https://github.com/buildpacks/docs/pull/655 fixes these build issues

**Comment by AidanDelaney** [comment]
We made a huge update to our docs. I'll rebase your changes on our latest updates.

**Comment by Srishti-j18** [comment]
Hi @AidanDelaney,
I find the documentation on Cloud Native Buildpacks very useful, especially for beginner contributors. I appreciate your efforts in keeping it well-documented. However, there are a few changes that I believe are required. It's great to see that you are actively updating the documentation.
I also wanted to bring your attention to an issue mentioned here: [issue 170](https://github.com/buildpacks/samples/issues/170#issuecomment-1935934611). I encountered the same problem while going through the documentation. If possible, could you address this issue? 
Additionally, let me know if I can contribute to resolving it.

**Comment by Srishti-j18** [comment]
> Hi @AidanDelaney, I find the documentation on Cloud Native Buildpacks very useful, especially for beginner contributors. I appreciate your efforts in keeping it well-documented. However, there are a few changes that I believe are required. It's great to see that you are actively updating the documentation. I also wanted to bring your attention to an issue mentioned here: [issue 170](https://github.com/buildpacks/samples/issues/170#issuecomment-1935934611). I encountered the same problem while going through the documentation. If possible, could you address this issue? Additionally, let me know if I can contribute to resolving it.

We can either mention explicitly about this  in the documentation manually, or we can address the issue by fixing the sample repository.

**Comment by AidanDelaney** [comment]
Thanks a lot.  This change is landed in https://github.com/buildpacks/docs/blob/main/content/docs/for-app-developers/how-to/build-inputs/use-cache-image.md#examples

**Pull request closed without merging**
