### PR TITLE
Made side-bar sticky

### PR DESCRIPTION
**Pull request by afzal442**
This PR makes dynamic sticky side-bar;

### CODE REVIEW

**Comment by jromero** [comment]
Could you explain the reasoning for proposing this change?

**Comment by afzal442** [comment]
> Could you explain the reasoning for proposing this change?

Sure! lemme share with you a screen recording of my proposal here. 
https://www.loom.com/share/44ece37154de4486b2e811d352301f45

HTMS!

**Comment by jromero** [comment]
The screen capture helps a lot. Thank you.

**Review by jromero — APPROVED** [review]

**Comment by jromero** [comment]
Thanks for the contribution!

It's nice to see the improvements.

**Pull request merged**
