### PR TITLE
Add -stack to removed flags in platform api 0.7

### PR DESCRIPTION
**Pull request by samj1912**
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>

### CODE REVIEW

**Comment by samj1912** [comment]
Actually, a bit confused now. https://github.com/buildpacks/spec/blob/platform/0.7/platform.md#exporter doesn't mention stack as a possible flag to exporter but looking at the lifecycle code and platform 0.8, it does exist.

**Comment by samj1912** [comment]
Ah, git blame to the rescue https://github.com/buildpacks/spec/pull/250

**Comment by samj1912** [comment]
I would prefer if we went back and fixed older released specs with typos.

**Comment by natalieparellano** [comment]
This should be closed, no? Since the spec is wrong...

**Pull request closed without merging**
