### PR TITLE
rename extension-author-guide to extension-guide

### PR DESCRIPTION
**Pull request by joe-kimmel-vmw**
with redirects

### CODE REVIEW

**Review by AidanDelaney — APPROVED** [review]
Thank you very much

**Comment by AidanDelaney** [comment]
Can you `git rebase -i --signoff main`?  And then force push the branch.

**Comment by joe-kimmel-vmw** [comment]
> Can you `git rebase -i --signoff main`? And then force push the branch.

✅   thanks @AidanDelaney

**Comment by natalieparellano** [comment]
@joe-kimmel-vmw would it be possible to fold this PR into https://github.com/buildpacks/docs/pull/581? That also expands on the extension guide and creates new links... apologies I didn't notice that earlier. Maybe we could pair on it?

**Pull request merged**
