### PR TITLE
Add contributor guide, link to community repo to community page

### PR DESCRIPTION
**Pull request by importhuman**
- Added the community repo link to the html
- I've made the other changes to the community.md file. I reckon it will require some formatting, as I could not preview the changes myself. Is there a way to see the changes locally? 
- Should I look at jinja for syntax details or somewhere else? 
- Could not add a link for working group in RFCs section as the current link is broken (please see [here](https://github.com/buildpacks/community/issues/108))
In addition to the above, please let me know if any changes are to be made to the content itself.

See #373 and #357

cc: @jromero

### CODE REVIEW

**Comment by jromero** [comment]
> I've made the other changes to the community.md file. I reckon it will require some formatting, as I could not preview the changes myself. Is there a way to see the changes locally?

Thanks @importhuman for the PR. To answer your question, you should be able to preview your changes locally by running `make serve`. More details (like dependencies) can be found here: https://github.com/buildpacks/docs/blob/main/DEVELOPMENT.md

> Could not add a link for working group in RFCs section as the current link is broken (please see here)

Good call out, the link is intended to be: https://github.com/buildpacks/community/#working-group

**Comment by importhuman** [comment]
@jromero I added the working group link and checked the preview locally, looks good to me. If there are any formatting or content changes to be made, please let me know.

Side note: `make serve` didn't work for me correctly, atleast not by itself. Following is the screenshot of the error message I received. 
Screenshot 2021-07-02 at 5 20 01 PM

I installed hugo with homebrew, after which `make serve` worked. Hopefully this was only an issue I encountered on my device, but thought I'd let you know in case this is weird.

**Comment by jromero** [comment]
@importhuman Sorry that this took so long to get in. It looks great. Thank you **so much** for the PR!

thanks

I might give it another pass at collapsing the content in tabs or something similar.

---

RE: "`make serve` didn't work for me correctly"

It sounds like you might have some missing go env configuration. The make task installs hugo but it doesn't look like it made it into your `$PATH`. You may run into other issues with `go install`. See if [this](https://golang.org/doc/gopath_code#GOPATH) helps:

```
export PATH=$PATH:$(go env GOPATH)/bin
```

**Review by jromero — APPROVED** [review]

**Comment by importhuman** [comment]
Thank you so much @jromero!

Regarding the `make serve` issue, I've installed it another way, so hopefully shouldn't be any trouble in the future.

> I might give it another pass at collapsing the content in tabs or something similar.

Would you like me to work on this?

**Pull request merged**
