### PR TITLE
Add Google Analytics and Dashboard

### LINKED ISSUE #346: Add Google Analytics integration to buildpacks.io
It would be great if the CNB project could add a Google Analytics integration and some sort of public-facing dashboard around this data to the website. The Paketo Buildpacks project has a site analytics [dashboard](https://datastudio.google.com/u/0/reporting/db924e17-d77d-4b13-8727-df635e775353/page/8KADB) and there's a lot of useful data that we get from this that we could use to inform decisions. 

For CNB, I'm very interested in seeing how a "notable" blog post, mention, or conference talk leads to an uptick in website visits and perhaps pack installs, and getting analytics setup similar to Paketo would be a good start towards trying to measure some of this.

### PR DESCRIPTION
**Pull request by jromero**
This change adds basic Google Analytics integrations as well as a link to the public [dashboard](https://datastudio.google.com/reporting/4b23856c-6c24-44f5-86f2-333d0ad3f236).

NOTE: Some fields are not populated yet due to the lack of data but should populate after a few days.

### Before
image

### After

image

image

Resolves #346

### CODE REVIEW

**Comment by kvedurmu** [comment]
This looks awesome @jromero. Really like that you've linked this dashboard in the footer (we should do this for Paketo). Thanks for resolving this so quickly!

**Comment by dfreilich** [comment]
This looks super super cool! One question - why is the registry linked with `DevStats`? The connection isn't clear to me

**Comment by jromero** [comment]
> This looks super super cool! One question - why is the registry linked with `DevStats`? The connection isn't clear to me

Bug...

**Comment by dfreilich** [comment]
Haha ok. Thanks for the quick turnaround

**Pull request merged**
